# Generated by Django 3.1.4 on 2021-01-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
